[global]
pid = /var/run/php-fpm82.pid
error_log = /var/log/php82/php-fpm.log
log_level = warning
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s
daemonize = no

include=/etc/php82/php-fpm.d/*.conf
